feat: add initial structure of record Page
blackwingedkite/cloudnative pull request #3
Opened 2023-12-05 16:06 UTC by ClipperSank

feat: add initial structure of record Page

2023-12-05 16:36 UTC, minchenlee commented on frontend/src/components/SearchBar.jsx
> +          onClick={() => setWeekPickerOpen(!weekPickerOpen)}>12/04 - 12/10
這邊的日期應該要跟日曆那邊一起更動，而不是寫死的。

2023-12-05 16:53 UTC, minchenlee commented on frontend/src/components/input/WeekPicker.jsx
> +    setSelectedWeek([startOfWeek.$d, endOfWeek]);
`setSelectedWeek([startOfWeek.$d` 後面那個 `$d` 是什麼寫法啊？可以解說一下嗎，感謝！

2023-12-05 17:15 UTC, minchenlee requested changes

2023-12-05 17:15 UTC, minchenlee commented on frontend/src/components/modals/CancelModal.jsx
> +  }
為什麼 Cancel Modal 裏面會有東西和招募球友相關，這邊的命名邏輯是什麼？
還有按下是以後應該是要去 Call 後端 API，雖然現在 API 還沒完全出來，但至少要寫一個空殼，讓之後在修改的時候可以一眼看出來要把 Call API 的邏輯加在哪裡。

2023-12-05 17:15 UTC, minchenlee commented on frontend/src/components/modals/CancelModal.jsx
> +  }
這邊為什麼是 navigate 到 /records，原本就在 /records 這個頁面了吧。
是不是應該 `setIsModalOpen(false)` 把 Modal 關掉？

2023-12-05 17:15 UTC, minchenlee commented on frontend/src/components/modals/DetailModal.jsx
> +  }, [weekData])
`console.log()` 檢查完記得註解掉。

2023-12-05 17:15 UTC, minchenlee commented on frontend/src/page/Records.jsx
> +        </div>
這邊其實可以用 && 來寫，可讀性會增加一些。

```javascript
{modalCategory === '招募球友' && ( 
<Modal width="38.75rem" height="23rem" title="招募球友" showClose={true} children={<FindMateModal />} />
)}

{ modalCategory === '查看詳細資訊'  && (
<Modal width="38.75rem" height="23rem" title="詳細資訊" showClose={true} children={<DetailModal />} />
)}

{ modalCategory === '取消預約' && (
<Modal width="38.75rem" height="23rem" title="取消預約" showClose={true} children={<CancelModal />} /> 
)}


{ modalCategory === '取消報名' && (
 <Modal width="38.75rem" height="23rem" title="取消報名" showClose={true} children={<CancelModal />} />
```

2023-12-07 08:22 UTC, ClipperSank commented on frontend/src/components/modals/CancelModal.jsx
> +  }
已將命名更改為適當的正確的名稱

且新增 `selectYes()` `selectNo()` 兩個 function 控制點擊是、否這兩個 button 的活動 
API 的邏輯應該也會加在這兩個 function 內

2023-12-07 08:33 UTC, ClipperSank commented on frontend/src/page/Records.jsx
> +        </div>
用 @minchenlee 提供的方法會發生進入該頁面後 
第一次點擊任何按鈕想要開啟 Modal 時
Modal 僅會顯示一瞬間並馬上消失
懷疑可能是在其他地方被 render 但是確切原因不知道 還在尋找
因此目前還是保留原本的寫法

2023-12-07 08:39 UTC, minchenlee commented on frontend/src/page/Records.jsx
> +        </div>
暸解，那這個可以就先這樣，不用管這個了，感謝！

2023-12-08 12:14 UTC, minchenlee approved these changes

2023-12-08 12:15 UTC, merged